{
  config,
  hostName,
  lib,
  ...
}: let
  isZenbook = hostName == "mrgeotech-zenbook";
  isPC = hostName == "mrgeotech-pc";
  isLaptop = hostName == "mrgeotech-laptop";

  # --- Monitors --------------------------------------------------------
  # The only thing Nix knows that Lua can't: which machine this is.
  monitors =
    if isPC
    then [
      {
        output = "DP-2";
        mode = "highres";
        position = "0x0";
        scale = 1;
      }
      {
        output = "HDMI-A-1";
        mode = "highres";
        position = "5120x0";
        scale = 1;
      }
    ]
    else [
      {
        output = "";
        mode = "highres";
        position = "auto";
        scale = 1;
      }
    ];

  luaMonitor = m: ''      { output = "${m.output}", mode = "${m.mode}", position = "${m.position}", scale = ${toString m.scale} },'';
  monitorsLua = lib.concatMapStringsSep "\n" luaMonitor monitors;

  # --- Theme (Catppuccin Mocha) ----------------------------------------
  # One palette, shared with hyprlock.nix. Nix owns it because more than one
  # program needs it; the whole attrset is handed to Lua as vars.colors.
  colors = import ./colors.nix;

  luaColor = name: value: ''    ${name} = "${value}",'';
  colorsLua = lib.concatStringsSep "\n" (lib.mapAttrsToList luaColor colors);

  # --- Misc host-conditional scalars -----------------------------------
  sensitivity =
    if isZenbook
    then "0.5"
    else "1";
  groupbarFontSize =
    if isZenbook
    then "18"
    else "12";
in {
  wayland.windowManager.hyprland = {
    enable = true;

    # Pin this. The default flips to "lua" at stateVersion 26.05, and the
    # hyprlang backend is deprecated for removal -- better to say it out loud
    # than to have a stateVersion bump silently rewrite your config format.
    configType = "lua";

    # UWSM (programs.hyprland.withUWSM in hosts/common/optional/hyprland.nix)
    # already manages the systemd session and exports HYPRLAND_INSTANCE_SIGNATURE.
    # Leaving this on too meant both were racing to export it -- uwsm's
    # wait-for-env-vars step would time out and tear the whole session down
    # before losing that race, which is what caused the login crash loop.
    systemd.enable = false;
    xwayland.enable = true;

    # `settings` stays empty on purpose. Everything lives in real .lua files
    # below, which get lua-language-server completion and Hyprland's own
    # LuaLS type definitions. home-manager writes hyprland.lua for us: it sets
    # package.path to ~/.config/hypr and emits a require() per autoLoad file,
    # in attribute-name order -- hence the numeric prefixes.
    extraLuaFiles = {
      # Generated: the host-conditional values, as a plain Lua module.
      "00-vars" = {
        autoLoad = false;
        content = ''
          -- GENERATED BY NIX (hypr/config.nix). Do not edit by hand.
          return {
            host = "${hostName}",
            home = "${config.home.homeDirectory}",

            monitors = {
          ${monitorsLua}
            },

            kb_options         = "caps:escape",
            sensitivity        = ${sensitivity},
            groupbar_font_size = ${groupbarFontSize},
            gestures           = ${lib.boolToString isZenbook},

            -- Only mrgeotech-laptop is hybrid graphics (Intel card0 + Nvidia
            -- card1, see hardware.nvidia.prime bus IDs in its host config).
            -- Forcing this on single-GPU hosts makes wlroots wait on a
            -- /dev/dri/card1 that never appears.
            drm_devices = ${
              if isLaptop
              then ''"/dev/dri/card0:/dev/dri/card1"''
              else "nil"
            },

            colors = {
          ${colorsLua}
            },
          }
        '';
      };

      # Helper module: required explicitly, never auto-loaded.
      "lib.keys" = {
        autoLoad = false;
        content = ./lua/lib/keys.lua;
      };

      "10-look-and-feel" = {
        autoLoad = true;
        content = ./lua/look-and-feel.lua;
      };
      "20-rules" = {
        autoLoad = true;
        content = ./lua/rules.lua;
      };
      "30-binds" = {
        autoLoad = true;
        content = ./lua/binds.lua;
      };
      "40-autostart" = {
        autoLoad = true;
        content = ./lua/autostart.lua;
      };
    };
  };
}
