{
  hostName,
  pkgs,
  ...
}:
let
  isZenbook = hostName == "mrgeotech-zenbook";
  isPC = hostName == "mrgeotech-pc";

  # --- Monitors -------------------------------------------------------
  monitorConfig = if isPC then [
    { output = "DP-2"; mode = "highres"; position = "0x0"; scale = 1; }
    { output = "HDMI-A-1"; mode = "highres"; position = "5120x0"; scale = 1; }
  ] else [
    { output = ""; mode = "highres"; position = "auto"; scale = 1; }
  ];

  luaMonitor = m: ''
    hl.monitor({ output = "${m.output}", mode = "${m.mode}", position = "${m.position}", scale = ${toString m.scale} })'';

  monitorsLua = builtins.concatStringsSep "\n" (map luaMonitor monitorConfig);

  # --- Misc host-conditional values ------------------------------------
  kbOptions = "caps:escape";
  sensitivity = if isZenbook then "0.5" else "1";
  groupbarFontSize = if isZenbook then "18" else "12";

  gestureLua = if isZenbook then ''
    hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
  '' else "";

  # --- Theme (Catppuccin Mocha, from your old mocha.conf) ---------------
  mauve = "rgb(cba6f7)";
  surface0 = "rgb(313244)";
  crust = "rgb(11111b)";
  overlay0 = "rgb(6c7086)";

  # --- Workspace binds (SUPER+[0-9] / SUPER+SHIFT+[0-9]) ----------------
  workspaceBinds = builtins.concatStringsSep "\n" (builtins.concatLists (
    builtins.genList (
      i:
      let ws = toString (i + 1); in [
        ''hl.bind(mainMod .. " + code:1${toString i}", hl.dsp.focus({ workspace = "${ws}" }))''
        ''hl.bind(subMod .. " + code:1${toString i}", hl.dsp.window.move({ workspace = "${ws}" }))''
      ]
    ) 9
  ));

  hyprlandLua = ''
    -- Generated by home-manager (config.nix) for Hyprland 0.55+ Lua config.
    -- See https://wiki.hypr.land/Configuring/Start/

    ------------------------------------------------------------
    -- DEBUG
    ------------------------------------------------------------
    hl.config({
      debug = { full_cm_proto = true },
    })

    ------------------------------------------------------------
    -- MONITORS
    ------------------------------------------------------------
    ${monitorsLua}

    ------------------------------------------------------------
    -- AUTOSTART
    ------------------------------------------------------------
    hl.on("hyprland.start", function()
      hl.exec_cmd("hyprpaper")
      hl.exec_cmd("systemctl --user start hyprpolkitagent")
      hl.exec_cmd("sh /home/mrgeotech/.config/hypr/scripts/wallpaper.sh")
      hl.exec_cmd("gnome-keyring-daemon --start --components=secrets")
      hl.exec_cmd("$BROWSER")
      hl.exec_cmd("bash -c \"sleep 0.5 && hyprlock\"")
    end)

    ------------------------------------------------------------
    -- ENV
    ------------------------------------------------------------
    hl.env("XCURSOR_SIZE", "24")
    hl.env("WLR_DRM_DEVICES", "/dev/dri/card0:/dev/dri/card1")

    ------------------------------------------------------------
    -- INPUT
    ------------------------------------------------------------
    hl.config({
      input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_rules = "",
        kb_options = "${kbOptions}",
        numlock_by_default = true,
        natural_scroll = false,
        follow_mouse = 1,
        touchpad = { natural_scroll = true },
        sensitivity = ${sensitivity},
      },
    })

    ------------------------------------------------------------
    -- GENERAL / GROUP / DECORATION / MISC
    ------------------------------------------------------------
    hl.config({
      general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 0,
        col = {
          active_border = "${mauve}",
          inactive_border = "${surface0}",
        },
        layout = "dwindle",
      },
      group = {
        col = {
          border_active = "${mauve}",
          border_inactive = "${surface0}",
        },
        groupbar = {
          font_family = "IosevkaTerm",
          font_size = ${groupbarFontSize},
          gradients = true,
          text_color = "${crust}",
          col = {
            active = "${mauve}",
            inactive = "${overlay0}",
          },
        },
      },
      decoration = {
        rounding = 0,
        active_opacity = 1.0,
        -- inactive_opacity = 0.85,
        dim_inactive = true,
        dim_strength = 0.1,
        blur = {
          enabled = true,
          size = 8,
          passes = 2,
          popups = true,
        },
      },
      binds = {
        movefocus_cycles_fullscreen = false,
        workspace_center_on = 1,
        focus_preferred_method = 0,
      },
      dwindle = {
        pseudotile = false,
        force_split = 0,
        default_split_ratio = 1.0,
      },
      master = {
        new_status = "slave",
      },
      misc = {
        disable_hyprland_logo = true,
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
      },
    })

    ${gestureLua}
    ------------------------------------------------------------
    -- WINDOW RULES
    ------------------------------------------------------------
    hl.window_rule({ match = { title = "^(.*rofi.*)$" }, dim_around = true })
    hl.window_rule({ match = { focus = true }, no_blur = true })

    ------------------------------------------------------------
    -- ANIMATIONS
    ------------------------------------------------------------
    hl.animation({ leaf = "global", enabled = true, speed = 3, bezier = "default" })

    ------------------------------------------------------------
    -- KEYBINDINGS
    ------------------------------------------------------------
    local mainMod = "SUPER"
    local subMod = "SUPER + SHIFT"
    local tetMod = "SUPER + CTRL"

    -- NOTE: this binds SUPER + SUPER_L (mainMod as a modifier, plus the
    -- Super key itself as the "key"), same as your old config. If you
    -- actually meant "just tap Super", bind to "SUPER_L" alone instead.
    hl.bind(mainMod .. " + SUPER_L", hl.dsp.exec_cmd("rofi -show run"))
    hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("ghostty"))
    hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("$BROWSER"))
    hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("ghostty -e yazi"))
    hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("steam"))
    hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd("flatpak run com.hypixel.HytaleLauncher"))
    hl.bind(mainMod .. " + Q", hl.dsp.window.close())
    hl.bind(subMod .. " + Q", hl.dsp.window.kill())
    hl.bind(mainMod .. " + E", hl.dsp.exit())
    hl.bind(subMod .. " + E", hl.dsp.exec_cmd("shutdown now"))
    hl.bind(subMod .. " + R", hl.dsp.exec_cmd("reboot"))
    hl.bind(mainMod .. " + W", hl.dsp.exec_cmd("pkill waybar && waybar"))
    hl.bind(mainMod .. " + S", hl.dsp.layout("togglesplit")) -- dwindle only
    hl.bind(subMod .. " + SPACE", hl.dsp.exec_cmd("rofi -show window"))
    hl.bind(subMod .. " + S", hl.dsp.exec_cmd("rofi -show ssh"))
    hl.bind("PRINT", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh region"))
    hl.bind(mainMod .. " + PRINT", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh activemonitor"))
    hl.bind(subMod .. " + PRINT", hl.dsp.exec_cmd("~/.config/hypr/scripts/screenshot.sh activewindow"))

    -- Move focus with mainMod + vim bindings
    hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
    hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
    hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
    hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))

    -- Move windows with subMod + vim bindings
    hl.bind(subMod .. " + L", hl.dsp.window.move({ direction = "right" }))
    hl.bind(subMod .. " + H", hl.dsp.window.move({ direction = "left" }))
    hl.bind(subMod .. " + K", hl.dsp.window.move({ direction = "up" }))
    hl.bind(subMod .. " + J", hl.dsp.window.move({ direction = "down" }))

    -- Resize windows with tetMod + vim bindings
    hl.bind(tetMod .. " + SHIFT + L", hl.dsp.window.resize({ x = 20, y = 0, relative = true }))
    hl.bind(tetMod .. " + SHIFT + H", hl.dsp.window.resize({ x = -20, y = 0, relative = true }))
    hl.bind(tetMod .. " + SHIFT + K", hl.dsp.window.resize({ x = 0, y = -20, relative = true }))
    hl.bind(tetMod .. " + SHIFT + J", hl.dsp.window.resize({ x = 0, y = 20, relative = true }))

    -- Move to next/previous workspace with mainMod + ['<','>']
    hl.bind(mainMod .. " + COMMA", hl.dsp.focus({ workspace = "r-1" }))
    hl.bind(mainMod .. " + PERIOD", hl.dsp.focus({ workspace = "r+1" }))

    -- Move window to next/previous workspace with subMod + ['<','>']
    hl.bind(subMod .. " + COMMA", hl.dsp.window.move({ workspace = "r-1" }))
    hl.bind(subMod .. " + PERIOD", hl.dsp.window.move({ workspace = "r+1" }))

    -- Scroll through existing workspaces with mainMod + scroll
    -- TODO: Fix (carried over from your old config's TODO)
    hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "r+1" }))
    hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "r-1" }))

    -- Layout toggles
    hl.bind(subMod .. " + F", hl.dsp.window.fullscreen({ mode = 0 }))
    hl.bind(subMod .. " + M", hl.dsp.window.fullscreen({ mode = 1 }))
    hl.bind(tetMod .. " + F", hl.dsp.window.float({ action = "toggle" }))

    -- Brightness control
    hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +10%"))
    hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-"))

    -- Player control
    hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"))
    hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
    hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

    -- Volume control
    hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%+"))
    hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%-"))
    hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle"))

    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with subMod + [0-9]
    ${workspaceBinds}

    -- Move/resize windows with mainMod + LMB/RMB and dragging
    hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
    hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
  '';
in {
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = true;
    xwayland.enable = true;
    # `settings`/`extraConfig` are intentionally unused: Hyprland 0.55+
    # loads ~/.config/hypr/hyprland.lua instead of hyprland.conf, and we
    # write that file ourselves below so we have full control over
    # dispatcher syntax. See https://wiki.hypr.land/Configuring/Start/
  };

  #home.file.".config/hypr/hyprland.lua".text = hyprlandLua;
}
