-- 30-binds.lua ----------------------------------------------------------------
-- Keybindings. Same layout as the old hyprland.conf, but the repetitive parts
-- are generated by Lua loops instead of by Nix.

local keys = require("lib.keys")

------------------------------------------------------------
-- MODIFIERS
------------------------------------------------------------
local mods = {
  main = "SUPER", -- launch / focus
  sub = "SUPER + SHIFT", -- move / destructive
  tet = "SUPER + CTRL", -- resize / modal
}

------------------------------------------------------------
-- PROGRAMS
------------------------------------------------------------
-- $BROWSER was a shell variable in the old config; in Lua we read the env
-- directly so a missing value fails loudly at one place instead of everywhere.
local browser = os.getenv("BROWSER") or "firefox"
local terminal = "ghostty"
local files = terminal .. " -e yazi"
local screenshot = "~/.config/hypr/scripts/screenshot.sh"

------------------------------------------------------------
-- LAUNCHERS & SESSION
------------------------------------------------------------
-- NOTE: this is SUPER held + the Super key itself, exactly as in the old
-- config. For a bare Super tap, bind "SUPER_L" with no modifier instead.
hl.bind(mods.main .. " + SUPER_L", hl.dsp.exec_cmd("rofi -show run"))

keys.map(mods.main, {
  { "T", hl.dsp.exec_cmd(terminal) },
  { "B", hl.dsp.exec_cmd(browser) },
  { "F", hl.dsp.exec_cmd(files) },
  { "G", hl.dsp.exec_cmd("steam") },
  { "Y", hl.dsp.exec_cmd("flatpak run com.hypixel.HytaleLauncher") },
  { "W", hl.dsp.exec_cmd("pkill waybar && waybar") },
  { "Q", hl.dsp.window.close() },
  { "E", hl.dsp.exit() },
  { "S", hl.dsp.layout("togglesplit") }, -- dwindle only
})

keys.map(mods.sub, {
  { "Q", hl.dsp.window.kill() },
  { "E", hl.dsp.exec_cmd("shutdown now") },
  { "R", hl.dsp.exec_cmd("reboot") },
  { "SPACE", hl.dsp.exec_cmd("rofi -show window") },
  { "S", hl.dsp.exec_cmd("rofi -show ssh") },
})

------------------------------------------------------------
-- SCREENSHOTS
------------------------------------------------------------
hl.bind("PRINT", hl.dsp.exec_cmd(screenshot .. " region"))
hl.bind(mods.main .. " + PRINT", hl.dsp.exec_cmd(screenshot .. " activemonitor"))
hl.bind(mods.sub .. " + PRINT", hl.dsp.exec_cmd(screenshot .. " activewindow"))

------------------------------------------------------------
-- MOTIONS: hjkl for focus, move, and resize
------------------------------------------------------------
-- One loop replaces twelve near-identical binds. Change the step size or the
-- modifier once and all three families follow.
local RESIZE_STEP = 20

keys.each_dir(function(letter, direction, vec)
  local L = letter:upper() -- modded binds use H/J/K/L, as the old config did

  -- Move focus
  hl.bind(mods.main .. " + " .. L, hl.dsp.focus({ direction = direction }))

  -- Move the window itself
  hl.bind(mods.sub .. " + " .. L, hl.dsp.window.move({ direction = direction }))

  -- Resize (SUPER + CTRL + SHIFT + hjkl), as before
  hl.bind(
    mods.tet .. " + SHIFT + " .. L,
    hl.dsp.window.resize({
      x = vec.x * RESIZE_STEP,
      y = vec.y * RESIZE_STEP,
      relative = true,
    }),
    { repeating = true }
  )
end)

------------------------------------------------------------
-- RESIZE SUBMAP (the one genuinely new binding)
------------------------------------------------------------
-- SUPER + CTRL + R enters a modal resize mode: hjkl resizes, held keys repeat,
-- Escape / Return / q leaves. This is the closest thing Hyprland has to a vim
-- operator-pending mode, and it was impossible to express cleanly in hyprlang.
hl.define_submap("resize", function()
  keys.each_dir(function(letter, _, vec)
    hl.bind(
      letter,
      hl.dsp.window.resize({
        x = vec.x * RESIZE_STEP,
        y = vec.y * RESIZE_STEP,
        relative = true,
      }),
      { repeating = true }
    )
  end)

  -- Bigger steps with shift, same letters.
  keys.each_dir(function(letter, _, vec)
    hl.bind(
      "SHIFT + " .. letter,
      hl.dsp.window.resize({
        x = vec.x * RESIZE_STEP * 5,
        y = vec.y * RESIZE_STEP * 5,
        relative = true,
      }),
      { repeating = true }
    )
  end)

  for _, exit_key in ipairs({ "escape", "return", "q" }) do
    hl.bind(exit_key, hl.dsp.submap("reset"))
  end
end)

hl.bind(mods.tet .. " + R", hl.dsp.submap("resize"))

------------------------------------------------------------
-- WORKSPACES
------------------------------------------------------------
-- code:10 .. code:18 are the physical 1-9 keys, so these survive a layout
-- change. Same mapping the Nix genList used to emit.
for i = 1, 9 do
  local code = "code:1" .. (i - 1)
  hl.bind(mods.main .. " + " .. code, hl.dsp.focus({ workspace = tostring(i) }))
  hl.bind(mods.sub .. " + " .. code, hl.dsp.window.move({ workspace = tostring(i) }))
end

-- Relative workspace movement on < and >
hl.bind(mods.main .. " + COMMA", hl.dsp.focus({ workspace = "r-1" }))
hl.bind(mods.main .. " + PERIOD", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mods.sub .. " + COMMA", hl.dsp.window.move({ workspace = "r-1" }))
hl.bind(mods.sub .. " + PERIOD", hl.dsp.window.move({ workspace = "r+1" }))

-- Scroll through workspaces
-- TODO (carried over from the old config): this never worked quite right.
-- If it still misbehaves, try "e+1"/"e-1" here instead of "r+1"/"r-1" --
-- e = existing-or-new, r = relative within the monitor's workspaces.
hl.bind(mods.main .. " + mouse_up", hl.dsp.focus({ workspace = "r+1" }))
hl.bind(mods.main .. " + mouse_down", hl.dsp.focus({ workspace = "r-1" }))

------------------------------------------------------------
-- LAYOUT TOGGLES
------------------------------------------------------------
hl.bind(mods.sub .. " + F", hl.dsp.window.fullscreen({ mode = 0 }))
hl.bind(mods.sub .. " + M", hl.dsp.window.fullscreen({ mode = 1 }))
hl.bind(mods.tet .. " + F", hl.dsp.window.float({ action = "toggle" }))

------------------------------------------------------------
-- MEDIA / BRIGHTNESS / VOLUME
------------------------------------------------------------
-- locked = true keeps these working while hyprlock is up; repeating = true
-- lets you hold the key. Both match what upstream's example config does now.
local media_opts = { locked = true, repeating = true }

keys.map("", {
  { "XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +10%") },
  { "XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 10%-") },
  { "XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%+") },
  { "XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_SINK@ 5%-") },
}, media_opts)

keys.map("", {
  { "XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_SINK@ toggle") },
  { "XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause") },
  { "XF86AudioNext", hl.dsp.exec_cmd("playerctl next") },
  { "XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous") },
}, { locked = true })

------------------------------------------------------------
-- MOUSE
------------------------------------------------------------
hl.bind(mods.main .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mods.main .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
